### ISSUE TITLE
Can not select correct language on Linux desktop

### ISSUE THREAD

**Issue by Yesterday17** [Tienisto/slang#102]
**Describe the bug**
Slang fallbacks to en on my desktop because the language tag received is `zh-UTF-8-CN`, which is not recognized by the regexp.

**To Reproduce**
1. Set locale to contain `UTF-8`

**Expected behavior**
Recognize and display the current language.

**Additional context**
Screenshot:
![image](https://user-images.githubusercontent.com/8667822/189473620-872ead22-4174-4d4f-b772-800f9fb1727e.png)

The output of `locale`:
```
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC=zh_CN.UTF-8
LC_TIME=zh_CN.UTF-8
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_ADDRESS=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL=
```

### Update

It seems to be an issue of flutter engine, which set charset as scriptCode in locale.
https://github.com/flutter/engine/blob/ce4156d519b94989684f508542b7cf644b6e7d67/shell/platform/linux/fl_engine.cc#L142

On slang side, maybe you should use `languageCode`, `scriptCode`, and `countryCode` properties directly instead of parsing the generated `languageTag`?

https://github.com/Tienisto/slang/blob/90d45806c83b81f2fe655d0cdb40f5089dda1ec1/slang_flutter/lib/slang_flutter.dart#L12-L17

**Comment by Tienisto** [comment]
Thank you. It is fixed in `v2.8.0`
