### ISSUE TITLE
Build failed on v2.8.0

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [Tienisto/slang#104]
**Describe the bug**
Flutter is 3.0.3 on my side. Yesterday everything was well. But today after upgrading to 2.8.0, my project builds failed.

**To Reproduce**
1. flutter run

Outputs
Error The method parseLocaleParts is not defined for class AppLocaleUtils

**Comment by Tienisto** [comment]
It seems that `slang_flutter` is upgraded to `2.8.0` but `slang` is not. Could you run `flutter clean` please?

**Comment by jinaiyuanbaojie** [comment]
> It seems that `slang_flutter` is upgraded to `2.8.0` but `slang` is not. Could you run `flutter clean` please?

Got it. I will try and let you know ASAP

**Comment by jinaiyuanbaojie** [comment]
You are right man. I close this ticket
