### ISSUE TITLE
Finds wrong slang.yaml

### ISSUE THREAD

**Issue by cpfeiffer** [Tienisto/slang#106]
We have a Jenkins job building flutter apps, and for each job, flutter is installed in the workspace directory, that is, in a sub directory of the flutter app. Example:
```
app/
  .flutter.git/
  slang.yaml
  pubspec.yml
  [...]
```

When we run `flutter pub run slang`, slang does not find the `slang.yaml` from the toplevel directory, but the example slang.yaml from the slang distribution in `.flutter.git/.pub-cache/hosted/pub.dartlang.org/slang-2.6.1/example/slang.yaml`

1. install flutter as a subdirectory of a flutter app, name it e.g. ".flutter.git"
2. run `flutter pub run slang`
3. see that it found the example slang.yaml and not the local one

**Expected behavior**
It should find the local slang.yaml

**Additional context**
https://github.com/Tienisto/slang/blob/master/slang/bin/slang.dart#L48

**Comment by Tienisto** [comment]
Thanks! It is fixed in `3.0.0-dev.0`. A stable release is coming soon.

**Comment by cpfeiffer** [comment]
Awesome, thank you very much!
