### ISSUE TITLE
Report of untranslated fields

### ISSUE THREAD

**Issue by elliotrtd** [Tienisto/slang#108]
When developing I often end up adding in more text fields as I go, normally in English (my first language). These then later need translating to our other supported languages which normally means sending other members of the team the JSON as txt. 

It's pretty easy to miss fields when doing this if I have a large tree, and I like to use default fallback to prevent build errors. 

With flutter_localizations (the suggested package for internationalization in the flutter docs) it produces a report of all fields which are untranslated (and which languages). 

This is another file generated by the build runner which can then easily be accessed, really makes life easy to just pull up a list. 

To make it even better would be to also list the english (or default) version in that file, essentially imitating the JSON structure, so I can literally just send this file to my team for translation.

**Comment by Tienisto** [comment]
Thanks for this idea!
This is available now on `v3.1.0`.
You can use it by typing this command: `flutter pub run slang:analyze`

**Comment by elliotrtd** [comment]
@Tienisto This is amazing, thanks! Used it today to catch some I'd forgotten to send to my team ;)
