### ISSUE TITLE
Is there a plan to support WEB

### ISSUE THREAD

**Issue by iyuhang** [Tienisto/slang#109]
Is there a plan to support WEB?

<img width="705" alt="image" src="https://user-images.githubusercontent.com/14176635/194689925-b23707f2-d2e9-4b8f-b4bf-40b3ad2f3e09.png">

<img width="701" alt="image" src="https://user-images.githubusercontent.com/14176635/194689938-e23901e9-d981-4827-8370-9fa72f181688.png">

**Comment by Tienisto** [comment]
`slang` supports web. The runner has some `dart:io` imports but it has no effect in your business code.
