### ISSUE TITLE
Dynamic parameter map

### ISSUE THREAD

**Issue by hamberluo** [Tienisto/slang#119]
**Motivation**
When I have both key for  t map and params map from server, I need call like this:

```dart
final value = t[key];
final s = value.replaceWithParam(params);
```

So map value need to be like 'my name is {{name}}' not ({required Object name}) => 'my name is ${name}'

**Comment by Tienisto** [comment]
Did you tried `String s = value(name: 'My Name')`?

**Comment by hamberluo** [comment]
> Did you tried `String s = value(name: 'My Name')`?

yes, but i use dynamic and source gen to implement this.

**Comment by Tienisto** [comment]
I see.
You want to interpolate the translations yourself.

Then you have 2 options:

**1: Translation Overrides**
You need to enable this feature in yaml config: `translation_overrides: true`.

```dart
// Initialize with translations that need to have dynamic parameters
  LocaleSettings.overrideTranslations(
    locale: LocaleSettings.currentLocale,
    fileType: FileType.json,
    content: '''
      {
        "myKey": "My name is {{name}}"
      }
      ''',
  );

  // All overrides of the current locale
  Map<String, Node> overrides = t.$meta.overrides;

  // "My name is ${name}"
  String content = (overrides['myKey'] as StringTextNode).content;
  
  // "My name is Tom"
  String a = content.applyParams({'name': 'Tom'});
```

**2: Custom String Interpolation**

You can just use your own string interpolation style which is not recognized by `slang`.

```json
{
  "myKey": "My name is {%name%}"
}
```

Then you need to write your own parsing algorithm.

**Comment by hamberluo** [comment]
Can I specify some json file to translation override and others not?

**Comment by Tienisto** [comment]
Yes, the override is per locale. You need to specify what locale will be overriden.

If you use namespaces, then the namespace name needs to be the root key.

**Comment by Tienisto** [comment]
Closed due to inactivity
