### ISSUE TITLE
Why does it force me to use t.translations.?

### ISSUE THREAD

**Issue by AlejandroEsquivel666** [Tienisto/slang#120]
Hi, I've been using slang and I have a question, why does the example use t.mainScreen.title and when generating the translations it forces me to use t.translations.mainScreen.title?

**Comment by Tienisto** [comment]
Please show your file name and file content. I cannot help you without any information

**Comment by AlejandroEsquivel666** [comment]
Hello, of course, sorry, here are the images, and it's strange because with another partner it works well, but with me it marks that error.
These are the file names
![route](https://user-images.githubusercontent.com/120405971/208719211-a0e6e5d4-007b-4f9e-aa6a-5a8420953384.PNG)
This is the content of the translations
![content](https://user-images.githubusercontent.com/120405971/208719514-01be88a8-4e77-431b-bb4e-0c0fe43ea298.PNG)
This is the error that shows me when trying to use it
![error](https://user-images.githubusercontent.com/120405971/208719709-4ce88de8-7930-4c20-8cb7-9b4a223e8ad2.PNG)

And the slang.yaml or build.yaml is the same as the example
![build](https://user-images.githubusercontent.com/120405971/208720194-2373e46f-dc76-4c11-9f0c-81857de9fd6a.PNG)

**Comment by Tienisto** [comment]
You need to set `namespaces: false` in the `build.yaml`.

**Comment by AlejandroEsquivel666** [comment]
Great, that was the problem, thank you very much, previously I removed options and according to me I had also removed that one and nothing, but I must have been confused.
