### ISSUE TITLE
Make the namespace types public

### ISSUE THREAD

**Issue by sketchbuch** [Tienisto/slang#121]
I store the namespace for a widget in a var to make it easier to access like this (simple example):

`final transBook = t.book;`

![image](https://user-images.githubusercontent.com/16445037/208837926-ae3168c7-3142-4c8e-a899-9890e600001c.png)

The type here is "_TranslationsBookEn" but I can't import that, so if I want to pass transBook as an argument I can't. Is there some reason why the namespace types can't be public?

I'm new to flutter and dart so maybe this is how it should be and i shouldn't be passing transBook around/using slang incorrectly.

**Comment by Tienisto** [comment]
Hello,

it is private by default to don't pollute the public namespace.
You can set translation classes public via `translation_class_visibility: public` in `slang.yaml` or `build.yaml` (checkout README)

**Comment by Tienisto** [comment]
Closed due to inactivity
