### ISSUE TITLE
Equals and hashCode for interfaces

### ISSUE THREAD

**Issue by lohnn** [Tienisto/slang#125]
**Motivation**
I've added a list of objects that are mapped to an interface. Then I use them dynamically to create a drop down menu. However, since the field in the generated translations Dart file uses a getter the assertion in the `DropDownButton` will never be true, as we are currently checking references and not content of the interfaced classes.  Generating equals and hashCode should be able to mitigate issues like this.

```Json
"interval(interface=Interval)": [
  {
    "type": "day",
    "title": "Dag"
  },
  {
    "type": "week",
    "title": "Vecka"
  },
  {
    "type": "month",
    "title": "Månad"
  },
  {
    "type": "year",
    "title": "År"
  }
]
```

```Dart
DropdownButton<Interval>(
  value: schedule.interval,
  items: [
    for (final interval in t.data.intervals)
      DropdownMenuItem(
        value: interval,
        child: Text(interval.title),
      ),
  ],
  onChanged: (value) {},
)
```

Another small micro example could look like this as well:
```Dart
t.data.intervals.first == t.data.intervals.first; // This is false
```

**Developer Experience**
Generating an equals and a hashCode function for the interfaces that runs equality checks on the fields to check if two instances holds the same field translations feels like the correct way to go about this.

**Comment by Tienisto** [comment]
Added in `v3.12.0`
