### ISSUE TITLE
Make an option to disable outputting metadata on generated file

### ISSUE THREAD

**Issue by noriHanda** [Tienisto/slang#126]
**Motivation**
My team and I are always frustrated when getting conflicts just by running `$ flutter pub run slang` since metadata on generated file such as generated date change even if original `strings.i18n.json` file is not changed. At the same time we do not want to gitignore the generated file since running the command every time a branch is changed is a pain.

**Developer Experience**
If there is an option to disable marking metadata on generated file, it would be better for people like us.

**Comment by Tienisto** [comment]
You can set `timestamp: false`

**Comment by noriHanda** [comment]
@Tienisto Oops my bad. Seems like I wasn't looking enough.
