### ISSUE TITLE
Support fallback translation on enums

### ISSUE THREAD

**Issue by Amphaal** [Tienisto/slang#130]
**Motivation**
I have an API endpoint which could return me some pre-determined text error codes, such as `notFound`, `notCompliant`, etc.
I'm translating them thanks to `slang` enum support. Unfortunately, since my API is not tightly bound to my Dart codebase, there could be drift, and my API could return at some point error codes that I have not handled yet in my app.
I could not find trace of such a feature in the current documentation, so I thought that a default param on enums translations could be beneficial in such usecases !

**Developer Experience**
In any `string*.i18n.*`, I guess we could do something like that, taking `_default` (as in `switch`'s `default` statement, could be `_fallback` or `_notFound` tho) as the magic fallback keyword.

<img width="549" alt="Capture d’écran 2023-03-13 à 09 51 36" src="https://user-images.githubusercontent.com/13903151/224652117-bfde3d07-f9f6-4bd8-a683-ce3bdf47032b.png">

**Comment by Amphaal** [comment]
Nevermind, I could just add the "fallback" into my enum, and make my error-code > enum parser redirect any non-matched names to it.

<img width="551" alt="Capture d’écran 2023-03-13 à 10 13 34" src="https://user-images.githubusercontent.com/13903151/224657288-78221e3f-35e2-487b-b96a-9ea6561a5895.png">

**Comment by Tienisto** [comment]
This is personal preference. Unless, you need the translation in multiple places, you can just implement an extension method. This way, you don't need to tell slang that the enum exist.

```dart
extension MyEnumExt on MyEnum {
  String get description {
    switch (this) {
      case MyEnum.firstState: return t.pairingRejection.noEmptyName;
    }
  }
}
```
