### ISSUE TITLE
Add updated translations to missing translations

### ISSUE THREAD

**Issue by adil192** [Tienisto/slang#132]
## Motivation
When a string is changed in the main (English) translation file, nothing is changed in `_missing_translations.json`.

My current strategy is to go through each translation file and delete the old translation, so that it shows up in `_missing_translations.json`, but this is a slow process. This also has the side effect that a non-English user is stuck with the untranslated new string rather than the translated old string (which would be better).

(Following https://github.com/adil192/saber/commit/31dd0dd95f087446eccb7468ea275a62b8d96f97#commitcomment-106405399, thanks @ceskyDJ)

<br/>

## Developer Experience
Consider this file for the English translation `strings.i18n.json`:
```json
{
  "meta": {
    "description": "This is the updated description"
  }
}
```

Devs can run a command like one of the following:
- `flutter pub run slang old t.meta.description`
- `flutter pub run slang obsolete t.meta.description`
- `flutter pub run slang stale t.meta.description`

Which would add an annotation to each non-English translation file, such as:
```json
{
  "meta": {
    "description(OLD)": "This is the old description in French"
  }
}
```

This has the advantage of keeping the old translation while still recording that it needs to be updated.

**Comment by Tienisto** [comment]
Thanks for raising this issue.

Added a new command in `v3.15.0`: `flutter pub run slang outdated meta.description` (without `t` because it is configurable)

**Comment by Tienisto** [comment]
I used the term "outdated" according to ChatGPT :)

![grafik](https://user-images.githubusercontent.com/38380847/228682948-045d0a05-fd9c-4724-bdbd-8d92ea032c33.png)
