### ISSUE TITLE
Wrong unused_translations.json result when variable is formatted in more than 1 line

### ISSUE THREAD

**Issue by wilyanto** [Tienisto/slang#133]
**Description**
Wrong information on `_unused_transalations.json` that generated from `flutter pub run slang analyze --full`  (example and how to reproduce attached)

![image](https://user-images.githubusercontent.com/53255602/229481654-4a6a25bd-8baa-4e93-9179-7715c2bd372f.png)

**To Reproduce**
Make a nested variable and called it in more than a line formatted, e.g:
```
t.profile.
  name
``` 
(new lined due to formatter suggestion), instead of
```
t.profile.name
```

Hope this issue will be solved. This feature is really helpful if the result is correctly aligned 👍

**Comment by wilyanto** [comment]
Hello @Tienisto, could you please take a look at this issue? Thank you before for the amazing package 😀

**Comment by Tienisto** [comment]
Thanks for raising this issue. This should be fixed in `v3.15.1`. Let me know if the error still exist!
