### ISSUE TITLE
option to skip null check with dynamic key

### ISSUE THREAD

**Issue by quockhanhh** [Tienisto/slang#136]
**Describe the bug**

recently our project has lots of file using dynamic key maps rerturning from backend. It has a case when the key not available in the language file it will show us the null check operator error because the library has the null check operator ( in api/locale.dart:16). we want some option like default string return to handle this error. Or just return empty string when the key is not available in the language file

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by Tienisto** [comment]
Hello,

The function is nullable but not the getter: https://github.com/Tienisto/slang/blob/master/slang/lib/api/locale.dart#L25

You should use the `[]` operator to access dynamic strings as stated in the [documentation](https://github.com/Tienisto/slang#-dynamic-keys--flat-map).

Also enable dynamic translations via `flat_map: true`.

**Comment by quockhanhh** [comment]
> Hello,
> 
> The function has a null check but not the getter: https://github.com/Tienisto/slang/blob/master/slang/lib/api/locale.dart#L25
> 
> You should use the `[]` operator to access dynamic strings as stated in the [documentation](https://github.com/Tienisto/slang#-dynamic-keys--flat-map).
> 
> Also enable dynamic translations via `flat_map: true`.

Thanks for the quick reply! Our project is already using this method you mentioned. It has a problem like this: 
    We have the function to get the dynamic key (which returned from backend) like "today" , "yesterday", ...  when we get the key like this and use for translate. it's work fine.
    But this function also return the custom key by user (our app has feature like folder management). The translator will return the null check operator used on null value( I don't know whether I am right or wrong but the debugger show the error in api/locale:16 and i see it has the ! operator) So i want some feature like return the key itself when it not available in the translate file. Or just return empty String or event  null value( without error). That will be awesome! :D Thanks for reading.

**Comment by quockhanhh** [comment]
> > Hello,
> > The function has a null check but not the getter: https://github.com/Tienisto/slang/blob/master/slang/lib/api/locale.dart#L25
> > You should use the `[]` operator to access dynamic strings as stated in the [documentation](https://github.com/Tienisto/slang#-dynamic-keys--flat-map).
> > Also enable dynamic translations via `flat_map: true`.
> 
> Thanks for the quick reply! Our project is already using this method you mentioned. It has a problem like this: We have the function to get the dynamic key (which returned from backend) like "today" , "yesterday", ... when we get the key like this and use for translate. it's work fine. (i use t["today"]) But this function also return the custom key by user(t["customkey"]) (our app has feature like folder management). The translator will return the null check operator used on null value( I don't know whether I am right or wrong but the debugger show the error in api/locale:16 and i see it has the ! operator) So i want some feature like return the key itself when it not available in the translate file. Or just return empty String or even null value( without error). That will be awesome! :D Thanks for reading.
> 
> i have set the flat_map to true

wait a minutes.. i see it's not the error im trying to describe

**Comment by quockhanhh** [comment]
Yea i see. The problem is when i have some dynamic key like t["customkey"] where the "customkey" is not available in any locale. The base  locale is return null (which is normal) for us to handle but the other locale is showing the null check operator error so we cant handle this case

**Comment by Tienisto** [comment]
You are correct. I could reproduce the error. This should be fixed in `v3.16.2`. Let me know if the error still occurs!

**Comment by quockhanhh** [comment]
Thanks a lot! The problem has been solved. Keep up the great job. I'm a big fan of your work!
