### ISSUE TITLE
[namespaces] support _ in file names

### ISSUE THREAD

**Issue by subzero911** [Tienisto/slang#144]
When I use underscore `_` or hyphen `-` in file names
<img width="251" alt="image" src="https://github.com/Tienisto/slang/assets/12999702/63496353-7882-480c-9dd0-40d05116bf7e">

`dart pub run slang` fails:

<img width="848" alt="image" src="https://github.com/Tienisto/slang/assets/12999702/ee0bdad8-32ed-481f-bb34-3bb016d581d2">

But when I remove `_` symbol
<img width="217" alt="image" src="https://github.com/Tienisto/slang/assets/12999702/a89621e6-de68-4c06-86e5-545ef03161b2">

Everything works fine:

<img width="495" alt="image" src="https://github.com/Tienisto/slang/assets/12999702/a660629c-bbc9-4eda-be78-40ce9b7f1f6e">

please support the `_` symbol
1) by convention in Dart files, words are in snake case
2) I originally used 'add_user' key everywhere in the app; when I splitted up my localization into namespaces, now I can't use it if it's in a file name.

my config:
<img width="375" alt="image" src="https://github.com/Tienisto/slang/assets/12999702/b6401647-6e81-4933-8518-fea0af3efd4b">

**Comment by subzero911** [comment]
Just noticed, `task_tracker` not fails for some reason, but the key is not generated.

Also, the whitespace in a filename is okay too ("add user"), but nothing's generated.

<img width="263" alt="image" src="https://github.com/Tienisto/slang/assets/12999702/9b7d30d0-d89e-4656-b060-e8535eb410cc">

**Comment by Tienisto** [comment]
Hello, as stated in the README (https://github.com/Tienisto/slang#-namespaces), you need to use camel case.

The reason is that slang needs to differentiate the namespace from the locale.

In your case, the files needs to be named `taskTracker.i18n.yaml` and `loginTracker.i18n.yaml`

**Comment by Tienisto** [comment]
This should be possible in `3.19.0` if you structure your code in sub folders:

```text
i18n/
  ru/
    - auth.i18n.yaml
    - login_blocked.i18n.yaml
  en/
    - auth.i18n.yaml
    - login_blocked.i18n.yaml
```

**Comment by samderlust** [comment]
@Tienisto  I tried snack_case on `3.26.2` but it doesn't work.  I change file name to camelCase, it works

> This should be possible in `3.19.0` if you structure your code in sub folders:
> 
> ```
> i18n/
>   ru/
>     - auth.i18n.yaml
>     - login_blocked.i18n.yaml
>   en/
>     - auth.i18n.yaml
>     - login_blocked.i18n.yaml
> ```
