### ISSUE TITLE
slang vs fast_i18n?

### ISSUE THREAD

**Issue by fzyzcjy** [Tienisto/slang#72]
Hi I wonder the difference between them?

**Comment by fzyzcjy** [comment]
That seems to be a problem :( Then users will import the whole code generator and make it a dependency of their app!

Maybe have a look at  json_serializable, freezed, ... etc to see how they do it :)

**Comment by Tienisto** [comment]
Alright, so you a concerned because of the library size? I don't think that this is really of an issue.
The merge is useful for #52 so I can reuse some parser functions.

**Comment by fzyzcjy** [comment]
Not only size, but also because then the (transitive) dependency has the `build` package.

**Comment by Tienisto** [comment]
The core logic will likely to be reused when #52 will be implemented

**Comment by fzyzcjy** [comment]
> Usually, I only run flutter pub run slang or flutter pub run fast_i18n because it is much faster :D

I also did that :)
