### ISSUE TITLE
Simplify namespace filenames

### ISSUE THREAD

**Issue by PoloLacoste** [Tienisto/slang#74]
**Motivation**
When we are using namespaces for example the one below:

```text
i18n/
 └── en/
      └── widgets.i18n.json
      └── dialogs.i18n.json
 └── fr/
      └── widgets_fr.i18n.json
      └── dialogs_fr.i18n.json
```

There is a bit of a repetition in the file names. 

**Developer Experience**
It would be interesting to simplify this like below:

```text
i18n/
 └── en/
      └── widgets.i18n.json
      └── dialogs.i18n.json
 └── fr/
      └── widgets.i18n.json
      └── dialogs.i18n.json
```

**Comment by Tienisto** [comment]
This should work in `slang v2.2.0` now.
