### ISSUE TITLE
rich text generate no param field

### ISSUE THREAD

**Issue by hamberluo** [Tienisto/slang#77]
```
{
  "myText(rich)": "Welcome $name. Please click ${underline(here)}!"
}
```

```
flutter pub run slang
```

```
	InlineSpan get myText => TextSpan(children: [
		const TextSpan(text: 'Welcome \$name. Please click \${underline(here)}!'),
	]);
```

there is no parameters for myText.

**Comment by Tienisto** [comment]
Hi. What is your `string_interpolation` configuration? It seems that you should use `{name}` or `{{name}}` instead of `$name`

**Comment by hamberluo** [comment]
> Hi. What is your `string_interpolation` configuration? It seems that you should use `{name}` or `{{name}}` instead of `$name`

thanks, i change to double braces string_interpolation and then fix it
