### ISSUE TITLE
Add Kotlin generator support

### ISSUE THREAD

**Issue by fzyzcjy** [Tienisto/slang#79]
I am considering to add a code generator to Kotlin (which my backend uses), such that I can write down some i18n json/yaml and use this library to generate kotlin i18n codes.

Will you accept the PR :)

**Comment by Tienisto** [comment]
That's sounds interesting! I use Kotlin for my backend too :)

**Comment by fzyzcjy** [comment]
After some examination, I realized there seems no need to modify slang to create a brand new i18n solution. Instead, I can just write a tiny code generator based on spring's `messages.properties` solution.
