### ISSUE TITLE
Is possible to have constant values?

### ISSUE THREAD

**Issue by BenevidesLecontes** [Tienisto/slang#88]
Hi, thanks for your amazing package. I'm wondering if is possible to generate constant variables instead of getters in cases where we don't have interpolation and another dynamic features.

**Comment by BenevidesLecontes** [comment]
I understand, but we have some use cases where we need a constant value. We can't use the getter in enhanced enums.

**Comment by Tienisto** [comment]
So you are only using one locale?
Because the translation variable itself is dynamic depending on the current locale

**Comment by Tienisto** [comment]
This is how I would implement it to make sure that always the current locale is used:

```dart
enum Vehicle {
  car,
  bike;
  
  String get description {
    switch (this) {
      case Vehicle.car:
        return t.vehicle.car;
      case Vehicle.bike:
        return t.vehicle.bike;
    }
  }
}
```
