### ISSUE TITLE
Rich Text cannot be parsed correctly

### ISSUE THREAD

**Issue by hamberluo** [Tienisto/slang#96]
current format only support space
```
"agreement(rich)": "you have read and agreed {{term(Terms of Service)}} and {{privacy(Privacy Policy)}}.",
```

param don't support
1. {{term(Terms-of-Service)}}
2. {{term(Terms of Service >)}}

another problem
result is camel case, but i need retain original text
```
		term('TermsOfService'),
		const TextSpan(text: ' and '),
		privacy('PrivacyPolicy'),
```

**Comment by Tienisto** [comment]
Both issues should be fixed in `v2.8.0`.
