### ISSUE TITLE
Chain RichText with pluralization

### ISSUE THREAD

**Issue by emersonsiega** [Tienisto/slang#99]
**Describe the bug**
I couldn't find in the documentation if this is possible... I need to chain the RichText and pluralization features.

This is the expected result, with pluralization and bold text:
singular:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/2227499/186913495-5154a5cf-34ab-4f90-b7dc-b49320f265bc.png">
plural:
<img width="199" alt="image" src="https://user-images.githubusercontent.com/2227499/186913515-92aaf8a0-4cd5-44c2-be8b-9de97a177fd5.png">

The configuration I'd tried:
```json
  "resultTitle(rich)": {
    "one": "{bold({count} ativo)} encontrado",
    "other": "{bold({count} ativos)} encontrados"
  }
```

The method generated:
```dart
String resultTitle({required num rich, required Object count}) => (_root._cardinalResolver ?? PluralResolvers.cardinal('pt'))(rich,
		one: '{bold($count ativo)} encontrado',
		other: '{bold($count ativos)} encontrados',
	);
//....

'search.resultTitle': ({required num rich, required Object count}) => (_root._cardinalResolver ?? PluralResolvers.cardinal('pt'))(rich,
   one: '{bold($count ativo)} encontrado',
   other: '{bold($count ativos)} encontrados',
),
```

The build_runner couldn't generate the code in a way that this two features work together.

**Comment by Tienisto** [comment]
Combining pluralization and rich text is currently not possible

**Comment by Tienisto** [comment]
Combining plural+rich text is now possible. You can try it out using `v3.0.0-dev.0`. I will release a stable release soon.

**Comment by Tienisto** [comment]
In your example, it will probably look like this:

```dart
"resultTitle(rich)": {
  "one": "{n} {bold(ativo)} encontrado",
  "other": "{n} {bold(ativos)} encontrados"
}
```

Then you can write your own builder util and call it twice:
```dart
TextSpan boldBuilder(Object content) {
  return TextSpan(
    text: content.toString(),
    style: const TextStyle(fontWeight: FontWeight.bold),
  );
}

Text.rich(t.resultTitle(
  n: n,
  nBuilder: boldBuilder,
  bold: boldBuilder,
));
```
